#!/bin/bash

# Start, restart, or stop the FastCGI Python instance.

PIDFILE=/tmp/django-fcgi-$USER-obal.pid

if [ -f $PIDFILE ]; then
    echo "Stopping...";
    kill `cat -- $PIDFILE`;
    rm -f -- $PIDFILE;
    sleep 1;
fi

if [ "$1" = "stop" ]; then
    echo "Stopped.";
else
    echo "Starting...";
    
    ME=`readlink -m $0`
    MYDIR=`dirname $ME`
    cd $MYDIR
    
    ./manage.py runfcgi host=localhost port=`echo 2000+$UID|bc` pidfile=$PIDFILE \
                     workdir=$MYDIR umask=0002 \
                     maxchildren=8 \
                     outlog=~/logs/obal_output_log errlog=~/logs/obal_error_log ;
fi

