#!/bin/bash

# Start, restart, or stop the FastCGI Python instance.

PIDFILE=/tmp/django-fcgi-$USER.pid

if [ -f $PIDFILE ]; then
    echo "Stopping...";
    kill `cat -- $PIDFILE`;
    rm -f -- $PIDFILE;
fi

HOSTNAME=`hostname -I | tr -d ' '` # assumes only one interface
PORT=`echo 1000+$UID|bc`

CTR=0
while [ "`netstat -tln |grep $PORT`" != "" ]; do
	if [ $CTR -gt 1 ]; then
		echo "Port still bound...";
		netstat -tln |grep $PORT;
	fi
	CTR=`echo $CTR+1|bc`
	sleep 1;
done

if [ "$1" = "stop" ]; then
    if [ -f /home/www/slave ] && [ "$USER" = "www" ]; then
        # Inform the master that we are no longer accepting connections.
        ./mysql_shell.sh -e "DELETE FROM farm WHERE hostport=\"$HOSTNAME:$PORT\";"
    fi

    echo "Stopped.";

else

    echo "Starting...";

    ME=`readlink -m $0`
    MYDIR=`dirname $ME`
    cd $MYDIR

    ./manage runfcgi host=$HOSTNAME port=$PORT pidfile=$PIDFILE \
                     workdir=$MYDIR umask=0002 \
                     maxchildren=8 \
                     outlog=~/logs/output_log errlog=~/logs/error_log ;

    if [ -f /home/www/slave ] && [ "$USER" = "www" ]; then
        # Inform the master that we are accepting connections.
        ./mysql_shell.sh -e "INSERT IGNORE INTO farm SET hostport=\"$HOSTNAME:$PORT\";"
    fi
fi
