#!/bin/bash

# rm database.sqlite
# LOCAL=1 LOADING_FIXTURE=1 ./manage syncdb
# LOCAL=1 ./manage syncdb # initializes MemberOfCongress, CongressionalCommittee tables
# LOCAL=1 LOADING_FIXTURE=1 ./manage loaddata data_testing/fixtures/*

LOCAL=1 DEBUG=1 ./manage runserver

