#!/bin/bash

# This is run as root. Pass the user name as the first argument.

useradd -m --shell /bin/bash $1
su $1 -c "cd; DB=$DB CODE=$CODE bash /home/ubuntu/inituser"
ln -s /home/$1/httpd.conf /etc/apache2/conf.d/$1.conf
ln -s /home/$1/nginx.conf /etc/nginx/conf.d/$1.conf

# run these if you're running this script separate from sysinit
#sudo service apache2 restart
#sudo service nginx restart
