#!/bin/bash

# This is to be executed by the ubuntu user to grab the current list of slave machines
# from the mysql farm table, update www's nginx.conf to update the fcgi backend list,
# and then restart nginx if any change was made.
#
# It is executed every minute by cron.

USERHOME=/home/www

SLAVES=
for host in `$USERHOME/sources/site/mysql_shell.sh -NBe "select hostport from farm"`; do
	SLAVES="$SLAVES\n\tserver $host; # AUTO FARM SLAVE"
done

grep -v "AUTO FARM SLAVE" $USERHOME/nginx.conf > /tmp/nginx.conf.new
sed -i -e "s/# SLAVE SERVERS HERE #/# SLAVE SERVERS HERE #$SLAVES/" /tmp/nginx.conf.new

if [[ `md5sum < $USERHOME/nginx.conf` != `md5sum < /tmp/nginx.conf.new` ]]; then
	sudo mv /tmp/nginx.conf.new $USERHOME/nginx.conf;
	sudo chown www.www $USERHOME/nginx.conf;
	sudo service nginx restart;
	echo Current slaves:
	echo $SLAVES;
else
	rm /tmp/nginx.conf.new
	if [[ "$1" != "-q" ]]; then
		echo no change
	fi
fi

